name: mini_project_chapter10
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  image_picker: 1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/Bg-Splash Screen.png
    - assets/Bg-Login Register.png
    - assets/Bg-Home Screen.png
    - assets/bunga.png
    - assets/gbr-login.png
  uses-material-design: true
